import time
import random
from random import randint
def main():
	print("Welcome to Guessing Game!")
	print("Written by Zhang Jiayu, 13851049.")
	#print welcome message and author's name.
	time.sleep(1)
	#use this to make clause appears gradually.
	little_num=1
	big_num=43
	score_dict={}
	global num
	num = random.randint(little_num,big_num)
	#set the range which could be change below or keep original default.

	while True:
		print("Menu:","\n","(I)nformation","\n","(V)iew High Scores","\n","(P)lay Game","\n","(S)et Game Limits","\n","(Q)uit")
		#print the menu and ask user for choosing.
		choose=str(input())
		if choose=="I" or choose=="i":
			print("This is a simple number guessing game.  When the game is played, the computer randomly generates a number between lower and upper bounds (inclusive). These default to 1 and 42, but the user can choose to change them to any valid numbers between 0 and a number greater than the lower bound.  Each player is prompted to provide name to start playing. The number of attempts to correctly guess the secret number generated by the computer is recorded.  When (Q)uit is selected, the program will display the list of players and their respective scores.  It will also display the player with the best score.")
			time.sleep(1)
			#print the information of the game and ask user to choose again.
		elif choose=="Q" or choose=="q":
			print("Farewell and thanks for playing")
			break
			#The choice"Q" is the finish of the progrem and display the farewell message.
		elif choose =="S" or choose=="s":
			print("Setting Game Limits.","\n","Low must be 0 or greater.","\n","High must be greater than low.")
			time.sleep(1)
			while True:
				low_number = input("Please enter a valid low bound integer!")
				if low_number.isdigit() and int(low_number) >= 0:
					break
					#make sure the input is digit.
			print('Low bound is {}'.format(low_number))
			while True:
				high_number = input("Please enter a valid high bound integer!")
				if high_number.isdigit() and int(high_number) > int(low_number):
					break
			print('High bound is {}'.format(high_number))
			num = random.randint(int(low_number), int(high_number))
			#use this two string to change the origin default above.
		elif choose == "P" or choose=="p":
			print("See if you can get a best score.")
			#print the "Hello" words.
			user_name = str(input("Hi, tell me your name"))
			#ask for user name.
			i = 0
			#set the variable
			while True:
				usernum = str(input("Guess the number:"))
				if not usernum.isdigit():
					print("Invalid guess")
					#in order to avoid crashing.
				else:
					if int(usernum) == num:
						print("You got it!")
						time.sleep(1)
						break
					elif int(usernum) < num:
						print("Your guess is too low.")
						i += 1
					else:
						print("Your guess is too high")
						i += 1
						#everytime users make mistakes, it will be calculated.
			print("Well done,","You guessed it in", i+1, "guesses.")
			score_dict[str(user_name)]=i+1
			#to record the name and grades into dictionary above.
		elif choose == "V" or choose=="v":
			if len(score_dict)==0:
				print("No player scores.")
				continue
				#tell user there are nothing in the dictionary.
			else:
				sorted(score_dict,reverse=True)
				for score_dic in score_dict:
					print(score_dic + '   ' + str(score_dict[score_dic]))
					#show elements of the dictionary.
		else:
			print("Invalid menu choice")
			#to avoid other inputs in order to avoid crashing.

main()